### ISSUE TITLE
Unhandled exception for annotated endpoint com.devicehive.proxy.client.WebSocketKafkaProxyClient

### ISSUE THREAD

**Issue by DurandA** [devicehive/devicehive-docker#57]
After upgrading to *devicehive-docker 3.5.0*, *dh_frontend* triggers errors related to websockets:
```
dh_frontend_1  | 2018-06-05 05:44:17.875 [XNIO-1 task-15] ERROR  io.undertow.websockets.core.request - UT025007: Unhandled exception for annotated endpoint com.devicehive.proxy.client.WebSocketKafkaProxyClient@5af40b11
dh_frontend_1  | java.lang.NullPointerException: null
dh_frontend_1  | 	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:1.8.0_162]
dh_frontend_1  | 	at com.devicehive.api.RequestResponseMatcher.offerResponse(RequestResponseMatcher.java:52) ~[devicehive-common-3.5.0.jar!/:3.5.0]
dh_frontend_1  | 	at com.devicehive.proxy.ProxyResponseHandler.handle(ProxyResponseHandler.java:69) ~[devicehive-proxy-ws-kafka-impl-3.5.0.jar!/:3.5.0]
dh_frontend_1  | 	at com.devicehive.proxy.client.WebSocketKafkaProxyClient.lambda$onMessage$0(WebSocketKafkaProxyClient.java:142) ~[devicehive-proxy-ws-kafka-impl-3.5.0.jar!/:3.5.0]
dh_frontend_1  | 	at java.util.Collections$SingletonList.forEach(Collections.java:4822) ~[na:1.8.0_162]
dh_frontend_1  | 	at com.devicehive.proxy.client.WebSocketKafkaProxyClient.onMessage(WebSocketKafkaProxyClient.java:109) ~[devicehive-proxy-ws-kafka-impl-3.5.0.jar!/:3.5.0]
dh_frontend_1  | 	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[na:na]
dh_frontend_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
dh_frontend_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
dh_frontend_1  | 	at io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$2.onMessage(AnnotatedEndpoint.java:142) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:281) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:162) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:159) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:575) ~[undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:561) [undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67) [undertow-websockets-jsr-1.4.20.Final.jar!/:1.4.20.Final]
dh_frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
dh_frontend_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
dh_frontend_1  | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```
These errors appear continously when using an [*android-ble*](https://github.com/devicehive/android-ble) device.

**Comment by sitnik** [comment]
@DurandA, hello,

Could you write steps to reproduce this issue?
